### PR TITLE
Remove bintray resolver and update dependencies

### PR DESCRIPTION
**Pull request by samanthagottlieb**
## What does this change?
We upgraded the `simple-configuration-ssm` library due to relying on an old version which was no longer available. As a result we needed to upgrade the Credentials Provider used by Amazon SDK.

## How to test

We ran the unit tests, then dry ran locally and then in CODE. Once merged we plan to do a dry run in PROD.

## How can we measure success?

Have a running program and maintaining functionality.

### CODE REVIEW

**Review by tjmw — APPROVED** [review]
I'm definitely not an expert on the AWS libs we're using here, but the change looks good to me!

**Comment by buck06191** [comment]
The changes all seem fine to me. It's worth deploying to CODE and doing a dry run to make sure it all runs. You can also do that locally _I think_, unless something changed since I last ran the code. 
As long as the dry run flag is set to `true`, it won't actually update any of the mailing lists. Just make sure that it's definitely set (I think not defining it also defaults to `true` but it's best to be safe)

**Review by buck06191 — APPROVED** [review]
LGTM bar a comment around testing it with a dry run to make sure it all still runs.

**Comment by arausuy** [comment]
> The changes all seem fine to me. It's worth deploying to CODE and doing a dry run to make sure it all runs. You can also do that locally _I think_, unless something changed since I last ran the code.
> As long as the dry run flag is set to `true`, it won't actually update any of the mailing lists. Just make sure that it's definitely set (I think not defining it also defaults to `true` but it's best to be safe)

We did this last week, both locally and in CODE. We'll also look to test a dry run in prod by explicitly setting the param store value to `true`. Hopefully, we can get a number of people rather than the zero we see in code.

**Comment by buck06191** [comment]
> > The changes all seem fine to me. It's worth deploying to CODE and doing a dry run to make sure it all runs. You can also do that locally _I think_, unless something changed since I last ran the code.
> > As long as the dry run flag is set to `true`, it won't actually update any of the mailing lists. Just make sure that it's definitely set (I think not defining it also defaults to `true` but it's best to be safe)
> 
> We did this last week, both locally and in CODE. We'll also look to test a dry run in prod by explicitly setting the param store value to `true`. Hopefully, we can get a number of people rather than the zero we see in code.

Ah yeah, there might actually be issues with the numbers that come through from CODE because I _think_  it uses the CODE data lake which doesn't contain data that actually gives sensible values. Checking PROD with dry run seems the best option there

**Pull request merged**
